### ISSUE TITLE
YAWL - Order @ JLCPCB - CPL-File

### ISSUE THREAD

**Issue by Masterbandit** [lizardsystems/yawl-controller#1]
Hi, 

I am interested in your controller and tried to order it at JLCPCB to create and assemble the pcb.
It is all working fine until the last step. When I add BOM and CPL and press Enter, it takes a long 
time and it appears the error "Incorrect format" "Failed processing the CPL file". I tried both BOMs
with the one CPL.

Can you please check this, I really want to try your nice controller.

Sincerely

Masterbandit

**Comment by vzagorovskiy** [comment]
Hi,
Do not download file from link

![image](https://user-images.githubusercontent.com/4923679/155546197-b40bc657-79d0-48bc-a30f-cfa9a0a4b48f.png)

 Please download zip file from main page https://github.com/lizardsystems/yawl-controller/

![image](https://user-images.githubusercontent.com/4923679/155546391-42df3bec-d674-4f2a-900c-16083ed6776a.png)
