### ISSUE TITLE
update bin

### ISSUE THREAD

**Issue by iamlite** [lizardsystems/yawl-controller#15]
Hey! Any chance for a firmware update for b3?

**Comment by numindast** [comment]
You can find the official binaries at the [Aircookie/WLED](https://github.com/Aircoookie/WLED/releases) github. You'd use the [WLED_0.14.0-b3_ESP8266.bin] firmware. You can also use https://install.wled.me/ which has a web-based tool to flash the firmware too. Note that this firmware does NOT include the Dallas temperature sensor usermod though.

**Comment by vzagorovskiy** [comment]
> Hey! Any chance for a firmware update for b3?

Done! https://github.com/lizardsystems/yawl-controller/tree/main/firmware/WLED

**Comment by iamlite** [comment]
Thank you!
