### ISSUE TITLE
maximum Current 

### ISSUE THREAD

**Issue by moonilightshaker** [lizardsystems/yawl-controller#2]
Hello, what are the maximum current for the Power traces?
Thanks

**Comment by vzagorovskiy** [comment]
All Christmas and New Year holidays the controller worked successfully with 200 LEDs on the Christmas tree. The temperature of the board did not exceed 35 degrees Celsius. By all calculations, if you strengthen the tracks as shown in the photo, the controller should work up to 8A-10A. If you need more, it is better to connect as shown in the diagram below.

![image](https://user-images.githubusercontent.com/4923679/171045330-45496694-69f9-4f22-aaf0-e5879adc0053.png)

**Comment by moonilightshaker** [comment]
Thanks for the Info.
