### ISSUE TITLE
Can this board also work with 12v?

### ISSUE THREAD

**Issue by mctigger** [lizardsystems/yawl-controller#5]
Hi,
I am wondering whether this board will work with 12v or needs some small modifications?

**Comment by vzagorovskiy** [comment]
You may use use a separate power supply or a dc-dc converter
![image](https://user-images.githubusercontent.com/4923679/174570799-e2a9d328-05e3-4104-ab52-c600e065549c.png)

**Comment by mctigger** [comment]
Thank you, so an additional buck-converter is needed.
