### ISSUE TITLE
Fuze F1 necessary? 

### ISSUE THREAD

**Issue by PhillipRt** [lizardsystems/yawl-controller#6]
Is the Fuze F1 (MF-PSMF050X-2) a required part or can I bridge it with solder? The part is out of stock everywhere.

**Comment by vzagorovskiy** [comment]
Hello, you may use C20978 or any 6V 500mA  0805 Resettable Fuses

![image](https://user-images.githubusercontent.com/4923679/184023425-23f99835-703b-4d2e-ade4-cb8d7b0b47a0.png)

**Comment by vzagorovskiy** [comment]
It is part of reverse polarity protection circuit. Yes,  you may not use this element, but it may not be safe if you accidentally reverse the power polarity.

**Comment by chunkysteveo** [comment]
https://lcsc.com/product-detail/Resettable-Fuses_BOURNS-MF-PSMF050X-2_C116170.html

180 in stock currently at time of posting this @PhillipRt
