### ISSUE TITLE
Ordering instructions for JLCPCB

### ISSUE THREAD

**Issue by habeas81** [lizardsystems/yawl-controller#8]
I've never ordered a PCB, though I've considered it many times.  I'd appreciate it greatly if this repo had an ordering guide for what options to choose in terms of the PCB production and assembly.  I'm happy to create it and commit it if you might be willing to help me walk through what I should choose on the website.  

Thanks in advance!  Awesome work and super grateful for you creating and sharing this.

**Comment by vzagorovskiy** [comment]
https://oshwlab.com/Daisy/How-To-Order-SMT-Service-From-JLCPCB-PCB-Components
